{% set name = "tkstyle" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tkstyle-{{ version }}.tar.gz
  sha256: 1318c36ba85e2e63fd8c8a333690a9b57064b4fd792513b47e0d51626a7570dc

build:
  entry_points:
    - tkstyle = tkstyle.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - tkstyle
  commands:
    - pip check
    - tkstyle --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/tkstyle
  summary: Create styles and themes for your Python desktop applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
